# Generated by Django 5.1.6 on 2025-03-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carregamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('carregamento', 'Carregamento'), ('descarregamento', 'Descarregamento')], default='carregamento', max_length=20)),
                ('data_carregamento', models.DateField()),
                ('hora_carregamento', models.TimeField(default='00:00:00')),
                ('numero_carregamento', models.CharField(max_length=100, unique=True)),
                ('peso', models.FloatField()),
                ('inicio_separacao_data', models.DateField(blank=True, null=True)),
                ('inicio_separacao_hora', models.TimeField(blank=True, null=True)),
                ('termino_separacao_data', models.DateField(blank=True, null=True)),
                ('termino_separacao_hora', models.TimeField(blank=True, null=True)),
                ('inicio_carregamento_data', models.DateField(blank=True, null=True)),
                ('inicio_carregamento_hora', models.TimeField(blank=True, null=True)),
                ('termino_carregamento_data', models.DateField(blank=True, null=True)),
                ('termino_carregamento_hora', models.TimeField(blank=True, null=True)),
                ('motorista', models.CharField(blank=True, max_length=100, null=True)),
                ('conferente', models.CharField(blank=True, max_length=100, null=True)),
                ('separador', models.CharField(blank=True, max_length=100, null=True)),
                ('observacao', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
